### ISSUE TITLE
Invalid token on web app

### ISSUE THREAD

**Issue by reyman** [etesync/etesync-web#123]
Invalid token.

t@https://client.etesync.com/static/js/2.8c493381.chunk.js:2:4080
t@https://client.etesync.com/static/js/2.8c493381.chunk.js:2:4163
M</e.prototype.newCall/</</<@https://client.etesync.com/static/js/2.8c493381.chunk.js:2:10734

Cannot add an event to my calendar :/

Best regards

**Comment by tasn** [comment]
Log out and log back in and that should fix it. Sorry for the delay in response.

I assume you haven't used the web app in a while, could that be the case? (this should now be properly handled in the most recent version).

I'm closing it as I just deployed a new version with the fix. Please let me know if it's still happening.

**Comment by andreasmjg** [comment]
Hi, this is still happening for me @tasn - almost every time I try to access pim.etesync.com. 

What am I doing wrong? I'm using Brave Browser

Thanks
Andreas
