### ISSUE TITLE
Missing paramater value completely crashes page load in web client

### ISSUE THREAD

**Issue by Niel0** [etesync/etesync-web#48]
I have a contact entry for Liverpool Victoria Insurance, which calls itself "LV=", Etesync seems completely thrown by that! In consequence, the web client won't load and syncing with android appears problematic. I've tried deleting the LV contact details and amending the "LV=" to read just "LV" but all seems frozen.... here's the full text copied/pasted from the web client:

Something went wrong!
Missing parameter value in 'ADR;TYPE=home;LABEL="LV=, County Gates, Bournemouth, BH1 2NF, UK":;;LV=\, County Gates;Bournemouth;;BH1 2NF;UK'
Stack trace:
    at new r (https://client.etesync.com/static/js/2.88819104.chunk.js:1:51083)
    at Function.i._handleContentLine (https://client.etesync.com/static/js/2.88819104.chunk.js:1:51957)
    at https://client.etesync.com/static/js/2.88819104.chunk.js:1:51261
    at Function.i._eachLine (https://client.etesync.com/static/js/2.88819104.chunk.js:1:54790)
    at Object.i [as parse] (https://client.etesync.com/static/js/2.88819104.chunk.js:1:51233)
    at https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:48778
    at t.__iterate (https://client.etesync.com/static/js/2.88819104.chunk.js:1:289129)
    at t.forEach (https://client.etesync.com/static/js/2.88819104.chunk.js:1:305541)
    at xr (https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:48725)
    at https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:89135

**Comment by tasn** [comment]
Are you by any chance able to send me this vcard? (annonymise parts as needed)

Thanks!

**Comment by Niel0** [comment]
Below is, I believe, the offending section from my contacts
'Niel Owen
=============================================
BEGIN:VCARD
VERSION:2.1
N:Insurance;Liverpool;Victoria (LV);;
FN:Liverpool Victoria (LV) Insurance
TEL;:080-003-22577
EMAIL;PREF;HOME:LV=.documents@lv.com
ADR;HOME:;;LV=, County Gates;Bournemouth;;BH1 2NF;UK
PHOTO;ENCODING=BASE64;JPEG:/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQE
 CAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/
 2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKC
 goKCgoKCgoKCgoKCgr/wAARCABgAGADASIAAhEBAxEB/8QAHQABAAICAwEBAAAAAAAAAAAAAA
 cIBAYCAwkFAf/EAE0QAAAEBQEEBAUMEAcAAAAAAAACAwQBBQYHEggJERMiFCEyQhUjMUNSFhc
 YJDVRVmJyh5XTGURIWGRxc3R1d4KDk5aX1ZKywcLR1OX/xAAbAQEAAQUBAAAAAAAAAAAAAAAA
 BQIDBAYHCP/EADMRAAECBAMEBgsBAAAAAAAAAAACAwQFBhIBBxQiIzJCExdSYnLSETNDVIKSk
 5SywuLw/9oADAMBAAIRAxEAPwD34AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQ
 +sNTV82klQeI1y7SUUbdwvexG/bMK911bxO7hkudXTqcllj9gnLIOIF9rlOVeJscYd7Ev+EQJ
 W3uK3/NRKOxxhv9dD9Ky//K5HmPJ6bzWOn60RMQtadvjWtf5EUh5zX2F24F6oQjAQjqSvenb2
 p0qfhMHqXQ2Kb2KDRbDpBlorJF4hsd+JeEbEufMY3xCibeXywiId1X2Fm1z5NCtqA4fqnlDVR
 NBiqpgjOmptxlJetGJoQ3HiWGB47uGpzekO2VpBTuY028zKl2vf70pwJS6wq/DXFfWz9zkLmz
 N7MqnotVHhVJTHKdduiX7bZd7jJ95I3KqXl5TYmF6KAryk7pUVKri0JPEZpJJ1L0nsrfob8HC
 ChciKF39fWWMPKPOicSzex6W2l71Fmor0ZZlNGhkXUtcQ7TRymYpYlOXum84Xm9IpMrSZMLq2
 DudNpRZ2rmTKm6vbKKzWVzTLostmHa8Jtk4FN44xCmKolyprGwMY3Jz8bobM1+SYLltQrXscy
 +PwqIuHi3NRYsu1eq7M1ky0KSoGYtEZomompPHrhKKxJYzjDLLHfCBlz7sUyRj1ZcQxTFhieq
 morWFWckYdDoq5E4k0Gaqft1N0U6xzENlvNxSmIbs8xTExN2Rg3yvTJ6Ska8mkL1aDaCiij14
 urms9cG5jrKG7x4xEIaY9M9wdpJc1d04fPZLaSQP+FUVQJwKReeuE1OeVM8ymhhy4OF/NlNw0
 /GZGRxmqgqvMao0rgFrYh0cFi7PiUXY2Kxxc00Nx9ot7qZ1e1WWxdgL8W3ni0rl1w6oZqzVFL
 hn4zFzTsyelSMYpjQ3FUTRNvKfzfaGsG1nVnCPVVTzf+VE7aqdIMi1EWypq3dP1AjSSlHzhN7
 TiyEoKu2a4s12XC6PA6cDJ8ByoUpSmLibD3sRCKmykusTfE2raVwh+rEv/AHhuVc0hWc7myXp
 bELQixPtlo2/Akqe1nSbkxvZqVn8LFf4o6/Zp198Klf4ph3G2T92DQ69Wcrh+O2X/ABMhxPsl
 7lR+6nlX9Mzf3IaZ1cZme/L+4X5y3dNe4RpVHRHzJBpHzjX/AGjhbKX2ntzx5tLYvWU0miSab
 57K545ZHcJpmMZMhuAsTKBIrK45ZY8Q4kWsdnjrOnnAlUtuXaTwfL4xSYruKYe9KcJ5cpl8lD
 wy+KXlL2eYa+fZd60PL67Nq/5ddiHhcqcwIX1O68C0+ct9FEIiL0IMk9y6e3e71T/zxMvrxJG
 ziuNNq3vNeGR+qGaPJNKUqcjK2U0nDl50c6zdyZYxeOc2OUSp5Y+iIoPss9Z3lhee2X0G9E+b
 P7RfXGkyNZ1DcavJXOZ1WblgddvJZeoi2aEapqJJ4mUNvNExT83KXHHvDoNAUdWEhn+pmS1Ka
 sVz3/viZTKoxxzfJPq6o9KsKqevrxWdkjKNTqtYJVBIFcUW1UNyY4kVP5t0SBfEuO72TcuJiV
 BnM4aSNl6rJI/XXlanETQXcci7RZPlVauS+bXJHlMX9oo9PYxhuyFUdZ2zZjqIdzCaWcuVChX
 dTqpp1eonLyrkVLA3NMG6fkI+gTIuRt6amXjC9rOZr3LVipHUxkJsO8/fKYqH6TDY4ykFpbIX
 X2kd2n9srfz19IKIk6qadb3AbJdbffzdBYGOUxFHpy/KK3TNxFO2kkt60WntbRFjrZyO01sJD
 CWU/TksTYypiRQ6nBRTLiUuR4mMaPxo74xHzNPunu0+le1Evs7ZOkkZNIJZxFEEE1DqHVVUNE
 6qyqh4mOqoc5jGMc280d43gxoFh1x3DeacpyDpyX6Zj5iuFhW4VsrHtLLlVVa5laV5T1WTOWN
 5pdHoM18GTBZr0hv4Bm63DUMkYuROIiifE3LkmQQMSu6IY9TZgv8Au5iv6Rjel75jG+UYWx1l
 aViar6NkVPta6jTz+nKjhNpW+jKSvUTqdDctDEVRMdPIvDdqeQ5eYpfL2RBBtlJdiMevVpJYf
 NYX+4Dmtd0nWc5nmplTy0IsTwPWB52Nbc3JpJ7n09+G/Szn6wfvrqU7780+l3P1g3L7E5eL77
 anv6Tf+kOlTZKXYjDfHVrT0PmsV/0mw0fq0zI54hf1v7Ma+a9hBeUAAepSUAAAAAAAAAAAAAA
 AAAAAAAAAAAAAAAAAAAAAAAAAAD//2Q==

NOTE;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=59=6F=75=72=20=70=6F=6C=69=63=79=20=6E=75=6D=62=65=72=3A=20=32=31=32=
=37=37=30=37=36=33=32=37=0A=0A=56=65=68=69=63=6C=65=20=20=20=20=20=20=
=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=43=
=6F=76=65=72=20=73=74=61=72=74=20=64=61=74=65=20=20=20=20=20=20=20=20=
=20=20=20=20=50=72=69=63=65=0A=43=56=36=31=55=4C=4B=20=20=20=20=20=20=
=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=20=31=32=20=41=75=67=
=75=73=74=20=32=30=31=38=20=20=20=20=20=20=20=20=20=20=20=20=20=C2=A3=
=32=34=34=2E=39=31
END:VCARD

**Comment by tasn** [comment]
Are you able to please send me the file directly by email (my first name at etesync.com) or post it as code using the GitHub web UI? It seems to be a bit mangled.

Thanks!

**Comment by tasn** [comment]
How was this entry created? Was it imported directly to the web client? Imported on the Android app? Imported from etesync-dav?

**Comment by Niel0** [comment]
That particular contact was exported, along with hundreds of my other contacts, from Google Contacts on one of my Android phones. I had installed Etesync on another Android phone and imported the contacts on that second phone which I thought I had set up to sync with Ete. It was on checking the Ete web client - to see if syncing was OK - that I discovered the issue I reported above.

**Comment by tasn** [comment]
OK, so it was first put into EteSync by the Android client. That's very weird! I'll have to figure out how this happened (unrelated to me fixing the web client, hopefully today or tomorrow) to stop erroring on this.

**Comment by Niel0** [comment]
The error now appears to have become complicated further as, today, I am unable to obtain anything from the web client other than the following error message (which appears different from the original!):

Something went wrong!

Missing parameter value in 'ADR;TYPE=home;LABEL="LV=, County Gates, Bournemouth, BH1 2NF, UK":;;LV=\, County Gates;Bournemouth;;BH1 2NF;UK'

Stack trace:

ICAL.parse</i._handleContentLine@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51957
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51261
ICAL.parse</i._eachLine@https://client.etesync.com/static/js/2.88819104.chunk.js:1:54790
i@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51233
xr/<@https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:48778
Zt</t.prototype.__iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:289129
forEach@https://client.etesync.com/static/js/2.88819104.chunk.js:1:305541
xr@https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:48725
867/qa</<@https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:89135
Ct</t.prototype.__iterate/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:279977
It.prototype.iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:284323
Ct</t.prototype.__iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:279946
forEach@https://client.etesync.com/static/js/2.88819104.chunk.js:1:305541
867/qa<@https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:89057
o/</c<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:321500
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:320929
o/</l<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:321630
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:320929
value@https://client.etesync.com/static/js/main.ede62a26.chunk.js:1:92946
Mo@https://client.etesync.com/static/js/2.88819104.chunk.js:1:763666
Co@https://client.etesync.com/static/js/2.88819104.chunk.js:1:763459
Io@https://client.etesync.com/static/js/2.88819104.chunk.js:1:767316
Ya@https://client.etesync.com/static/js/2.88819104.chunk.js:1:786901
qa@https://client.etesync.com/static/js/2.88819104.chunk.js:1:787285
Ts@https://client.etesync.com/static/js/2.88819104.chunk.js:1:793831
ks@https://client.etesync.com/static/js/2.88819104.chunk.js:1:793211
_s@https://client.etesync.com/static/js/2.88819104.chunk.js:1:792232
Ga@https://client.etesync.com/static/js/2.88819104.chunk.js:1:791135
enqueueSetState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:745356
w.prototype.setState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:696954
t/r.handlePersistorState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:620606
v@https://client.etesync.com/static/js/2.88819104.chunk.js:1:248700
d@https://client.etesync.com/static/js/2.88819104.chunk.js:1:337169
k@https://client.etesync.com/static/js/2.88819104.chunk.js:1:335015
w/</</<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:335624

**Comment by tasn** [comment]
That's expected unfortunately. The error handling in the web client is very aggressive at the moment. Once it fails, it fails. I'll have to fix your specific issue for you to be able to use it. Though I suspect it may be an issue with ical.js, our parser.

**Comment by tasn** [comment]
Relevant issue: https://github.com/mozilla-comm/ical.js/issues/187

They don't seem to support vCard 2.1 yet (though there's a recent and fairly complete PR it seems). It means I'll have to figure out how to work around it. I'm just surprised it was even created in the first place. The Android client is only meant to generate vCard 4. I'll try to import your broken vCard later today or early tomorrow and hopefully be able to at least work around this in the web client.

**Comment by tasn** [comment]
Having gone through the Android code again, I don't see how this event could have come from there. We only write vCard 4.0, never 2.1. Are you absolutely certain you just imported it to Android and that's it?

**Comment by Niel0** [comment]
I have a Samsung S8 running Lineage 16 & MicroG, so no Google services. I
chose Ete to sync contacts & calendar on that S8 (and a second S8 I was
going to set up similarly as my wife's spare phone).

I exported my Google contacts on my Samsung S4 Tab & copied the file to the
S8 where I had set up Ete as sync provider for contacts. I imported the
contacts on the S8 & manually synced with Ete. The rest you know....


'Niel Owen
══════════════════
Daniel JG Owen
Delfarch
Stryd yr Eglwys / Church Street
Llanrhystud
Ceredigion
Cymru / Wales
SY23 5DQ

nielowen@gmail.com
══════════════════

**Comment by Niel0** [comment]
Correction - I've now checked and found I also set up the S4Ttab to sync
conacts & calendar with Ete and that has now thrown up errors - I am
forwarding the error log to you.

**Comment by tasn** [comment]
Sorry it took me so long to investigate.

Findings:
1. As I said above, EteSync on Android does in fact convert the vCard to vCard 4.0.
2. I can reproduce the web client issue.
3. It works fine in etesync-dav.
4. It works fine in Thunderbird.

The problem is with this line: `ADR;LABEL="LV=, County Gates\nBH1 2NF Bournemouth\nUK";TYPE=home:;;LV=\, Co` and more specifically the `;LV=\,` part.

It seems to me that this vCard is in fact legal and the problem is with the upstream library.

Issue reported upstream: https://github.com/mozilla-comm/ical.js/issues/402

I'll take a look into maybe switching to: https://github.com/enesser/vCards-js

**Comment by tasn** [comment]
Another comment: I think in general we need to be more defensive about malformed data and not completely crash.

**Comment by bcode2** [comment]
I have just opened  the web client and BOOMM , the same  problem
Stack trace:

ICAL.parse</i._handleContentLine@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51957
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51261
ICAL.parse</i._eachLine@https://client.etesync.com/static/js/2.88819104.chunk.js:1:54790
i@https://client.etesync.com/static/js/2.88819104.chunk.js:1:51233
xr/<@https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:48824
Zt</t.prototype.__iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:289129
forEach@https://client.etesync.com/static/js/2.88819104.chunk.js:1:305541
xr@https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:48771
867/qa</<@https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:89351
Ct</t.prototype.__iterate/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:279977
It.prototype.iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:284323
Ct</t.prototype.__iterate@https://client.etesync.com/static/js/2.88819104.chunk.js:1:279946
forEach@https://client.etesync.com/static/js/2.88819104.chunk.js:1:305541
867/qa<@https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:89273
o/</c<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:321500
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:320929
o/</l<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:321630
i/<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:320929
value@https://client.etesync.com/static/js/main.59c3899d.chunk.js:1:93179
Mo@https://client.etesync.com/static/js/2.88819104.chunk.js:1:763666
Co@https://client.etesync.com/static/js/2.88819104.chunk.js:1:763459
Io@https://client.etesync.com/static/js/2.88819104.chunk.js:1:767316
Ya@https://client.etesync.com/static/js/2.88819104.chunk.js:1:786901
qa@https://client.etesync.com/static/js/2.88819104.chunk.js:1:787285
Ts@https://client.etesync.com/static/js/2.88819104.chunk.js:1:793831
ks@https://client.etesync.com/static/js/2.88819104.chunk.js:1:793211
_s@https://client.etesync.com/static/js/2.88819104.chunk.js:1:792232
Ga@https://client.etesync.com/static/js/2.88819104.chunk.js:1:791135
enqueueSetState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:745356
w.prototype.setState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:696954
t/r.handlePersistorState@https://client.etesync.com/static/js/2.88819104.chunk.js:1:620606
v@https://client.etesync.com/static/js/2.88819104.chunk.js:1:248700
d@https://client.etesync.com/static/js/2.88819104.chunk.js:1:337169
k@https://client.etesync.com/static/js/2.88819104.chunk.js:1:335015
w/</</<@https://client.etesync.com/static/js/2.88819104.chunk.js:1:335624

**Comment by tasn** [comment]
@bcode2, do you know which entry breaks it for you by any chance? I wonder if it's the same issue as @Niel0's or not.

**Comment by bcode2** [comment]
Yes  this is  the  first part of the  error. I have  checked  that  contact  and  looks  pretty ugly  in my phone. Will delete it  and  check weather  the error  disappears
Something went wrong!

Missing parameter value in 'ADR;TYPE=work;LABEL="Carretera de Fuencarral, 70, 28108, Alcobendas, Madrid\nAlcobendas, Madrid\nBAQECAGICAGQDAGICAGUEBAMEBGUGBGYFBGYGBWK

**Comment by tasn** [comment]
Do you have the full entry? You can get it e.g. from the journal log on Android. Maybe it's an old vCard format? vCard is an infinite source of issues it seems. :)

**Comment by bcode2** [comment]
I have checked it  and  it is version 4. BTW why  if I have deleted the  entry,  the   FATAL ERROR still appears in  my web client and  does not  allow me to do any thing  ?

**Comment by tasn** [comment]
Yeah, the reason for that is that EteSync needs to parse all past and current vcards to build the correct state, so even if you delete it, it still needs to be parsed at least one. The easiest way to solve this for you is for me to solve the root cause. :)

Are you able to send me the problematic vcard in a secure channel? Or better yet, put it here, but just replace the name with AAAA and the number with 00 or something? Would be easiest to solve it if I could reproduce it locally.

**Comment by bcode2** [comment]
I am trying to  copy  the  raw version  of that entry  in the journal  and the  application  do not  allow me to do that. No select all option neither copy version  appears

**Comment by tasn** [comment]
Grrr. I just released version 1.8.0 that fixes this issue - you can now select and copy the raw entry.
Here's the apk signed with the release key, so if you installed from google play, you can just use it directly.

https://stosb.com/~tom/entry-selectable.apk

Sorry about this.

**Comment by bcode2** [comment]
I have  just  sent you the  vcard by mail

**Comment by tasn** [comment]
Replied there, though please, if you can, send me the vcard exactly as it appears in the change journal (by e.g. using the fixed apk above).

**Comment by bcode2** [comment]
Ok, sent  using  the  new APK  version

**Comment by tasn** [comment]
I keep on trying, and doesn't matter what I do to the file, it doesn't parse on the web client. I need to stop investigating it for a bit unfortunately. If you use the web client, and this is preventing you from using it, please reach out by email and I'll help you sort it out for you locally, though fixing the overarching issue: it'll take a bit more.

**Comment by bcode2** [comment]
Ok dont  worry take your time  to fix the bug , it is not urgent . I don't use the  web client very often
Regards

**Comment by bcode2** [comment]
Hello, I wold like to get this problem sorted out. Any advance  in my issue?
I am still getting  the error below and  I am not able to  see the  journal.

Something went wrong!

Missing parameter value in 'ADR;TYPE=work;LABEL="Carretera de Fuencarral, 70, 28108, Alcobendas, Madrid\nAlcobendas,

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tasn** [comment]
Should now be fixed, thanks for the reminder. :)

Please let me know if it's not the case.

**Comment by bcode2** [comment]
Nop sorry , the  issue remains . Now I have  a lot  of parse errors.
See Screenshots below

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tasn** [comment]
There are no screenshots in your comment.

Just to clarify though, you see the parse errors at the top right, but you can still use the web client (other than the errors appearing), correct? Because if so, that's as intended. There are real errors here, but they are just non-fatal so we log them, show them, and let you continue using the web app.

**Comment by bcode2** [comment]
The problemnow is that I can't see the contact journall

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by tasn** [comment]
What's the problem you are getting now exactly? Could you provide more information? After this patch it should just skip the broken entries (and add them to that broken entries list) and show everything (other than the broken entries) correctly.
What do you mean exactly by "can't see the contact journal", where are you looking and what are you getting?

**Comment by bcode2** [comment]
Hello
If I try  to  see the  journal  entries I receive  the  following message. See the screenshot
[error01.png]

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tasn** [comment]
Still no screenshot. Could you maybe try using the GitHub UI directly for uploading the image?

Thanks!

**Comment by bcode2** [comment]
Here  is the  screnshot. I have checked  the emails  and  the attachments are there ;(
![error01](https://user-images.githubusercontent.com/47030277/69267700-9edd7d80-0bc5-11ea-866e-51b20ef8a995.png)

**Comment by tasn** [comment]
OK, so same error. I'm looking into this...

**Comment by tasn** [comment]
I didn't realise you were talking about looking at the journal change log. The previous fix only fixed the sync. :)

It should now be fixed.

**Comment by bcode2** [comment]
Yes, fixed
Thankssss

**Comment by tasn** [comment]
Yay \o/

No problem. :)
