### ISSUE TITLE
duckduckgo chrome plug-in is giving the website a B for no privacy practices found

### ISSUE THREAD

**Issue by wireddude** [etesync/etesync-web#7]
Noticed this, this morning, duckduckgo chrome plug-in is giving the website a B for no privacy practices found

![screen shot 2018-01-23 at 10 50 35 am](https://user-images.githubusercontent.com/5432629/35294414-5f013eec-002b-11e8-8670-46ccfdbc046c.png)
![screen shot 2018-01-23 at 10 50 26 am](https://user-images.githubusercontent.com/5432629/35294415-5f194ca8-002b-11e8-9d6b-31f1248cf80b.png)

TOS;DR links here: https://tosdr.org/

**Comment by tasn** [comment]
Damn them. It's a just crazy to give such a strong indicator (demoting to a B) because EteSync is not listed on a third party ToS rating website.

Thank you for letting me know. I'll make sure to get EteSync added ASAP.

For reference, this is the EteSync privacy policy: https://www.etesync.com/tos/

Note: this also affects the main website.

**Comment by tasn** [comment]
Apparently you can't add a new service unless you are an admin, so I sent them an email.
Will update as I get more info.

**Comment by tasn** [comment]
Done, and added some points that describe the EteSync service's terms.
I'm obviously biased though, so I encourage others to review/correct anything you think I may have done wrong. Link: https://edit.tosdr.org/services/329

Waiting for the tosdr moderators to approve the points so the extension will pick this up.

**Comment by tasn** [comment]
Slow to approve points. :(

**Comment by tasn** [comment]
They approved the points, so now we just need to wait for DDG to update the plugin I guess, as for me it still says it's missing.

**Comment by rugk** [comment]
I think this issue is solved. And good you got added to that website – come on, it's also advertisement for you… :wink:

**Comment by tasn** [comment]
It's still showing as unknown. :|
I don't know, maybe we need to chase the DDG people...

**Comment by tasn** [comment]
I did what I could there. I don't think they've moved to the new system yet, so it's STILL not showing. Anyhow, nothing left to do here.
